# Cloudflare Pages configuration for 요르의 투자 플랫폼
name = "yor-investment-platform"
compatibility_date = "2024-08-12"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "yor-investment-platform"
routes = [
  { pattern = "yourinvestment.pages.dev", zone_name = "yourinvestment.pages.dev" }
]

[env.preview]
name = "yor-investment-platform-preview"

# Environment variables (set these in Cloudflare dashboard)
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://yor-investment-platform.pages.dev"

# Build configuration for Cloudflare Pages
[[pages_build_output_dir]]
name = ".vercel/output/static"

# Functions configuration
[build]
command = "npm run pages:build"
cwd = ""
watch_dir = ""

# Compatibility settings for Next.js
[compatibility_flags]
nodejs_compat = true

# Custom headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache settings for static assets
[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=86400"

# Redirects
[[redirects]]
from = "/api/health"
to = "/api/gateway/health"
status = 301